# Generated by Django 3.2.2 on 2021-05-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_contact_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='address',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='full_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='relationship',
            new_name='name',
        ),
    ]
